# Generated by Django 3.1.4 on 2023-11-20 00:49

from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import django_super_survey.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=3000, verbose_name='text')),
                ('type', models.CharField(choices=[('text', 'text (multiple line)'), ('short-text', 'short text (one line)'), ('radio', 'radio'), ('select', 'select'), ('select-multiple', 'Select Multiple'), ('integer', 'integer'), ('float', 'float'), ('date', 'date')], default='text', max_length=200, verbose_name='type')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('order', models.IntegerField(verbose_name='order')),
                ('is_required', models.BooleanField(default=False)),
                ('allow_add_choice', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='name')),
                ('slug', models.SlugField(blank=True, max_length=300, verbose_name='slug')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('image', models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media/', location='/var/www/media/'), upload_to=django_super_survey.models.make_survey_image_path)),
                ('vote_require_login', models.BooleanField(default=False)),
                ('results_require_login', models.BooleanField(default=False)),
                ('allow_multiple_answers', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
                ('publish_date', models.DateField(blank=True, null=True, verbose_name='publication date')),
                ('expire_date', models.DateField(blank=True, null=True, verbose_name='expiration date')),
                ('is_single_page', models.BooleanField(default=False)),
                ('done_url', models.TextField(blank=True, max_length=1000, null=True, verbose_name='done URL')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=3000, null=True, verbose_name='description')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('value', models.CharField(max_length=200, verbose_name='value')),
                ('order', models.IntegerField(verbose_name='order')),
                ('image_url', models.CharField(blank=True, max_length=1000, null=True, verbose_name='image URL')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='django_super_survey.question', verbose_name='question')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='django_super_survey.survey', verbose_name='survey'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=200, verbose_name='value')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='update date')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='django_super_survey.question', verbose_name='survey')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_answers', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
